#!/bin/bash

/usr/local/ncbi-blast-2.2.28+/bin/makeblastdb -in L1_1st_primer.fasta -dbtype nucl
/usr/local/ncbi-blast-2.2.28+/bin/blastn -task blastn-short -query human_g1k_v37.fasta -db L1_1st_primer.fasta -out Reference_L1HS_1st_blastn-short.bed -outfmt "6 qseqid qstart qend bitscore evalue sstrand"
cat Reference_L1HS_1st_blastn-short.bed| awk '{ print "chr"$1"\t"$2"\t"$3"\t"$4"\t"$5"\t"$6}' > temp_chr_L1_1st.bed
mv temp_chr_L1_1st.bed Reference_L1HS_1st_blastn-short.bed
intersectBed -a ../ref_mescan/hg19.fa.bed -b Reference_L1HS_1st_blastn-short.bed -wa -wb > Reference_L1HS_1st_blastn-short_intersect_RM.bed   #97.8% intersect with Repeat Masker file
cat Reference_L1HS_1st_blastn-short.bed|sort -V -k1,3 > sorted_reference_L1HS_1st_blastn-short.bed	#input for the "contain_both_L1HS_primer.py"
cat Reference_L1HS_Ewing_2010_blastn-short.bed|sort -V -k1,3 > sorted_reference_L1HS_Ewing_2010_blastn-short.bed


